//page status
export const CANGE_LOCALE = 'CANGE_LOCALE';
export const CANGE_LANG = 'CANGE_LANG';
export const SIDEVAR_ON = 'SIDEVAR_ON';
export const SIDEVAR_OFF = 'SIDEVAR_OFF';
export const CHANGE_SIDEVAR = 'CHANGE_SIDEVAR';

//request my profile
export const REQUEST_MY_PROFILE = 'REQUEST_MY_PROFILE';
export const REQUEST_MY_PROFILE_SUCCESS = 'REQUEST_MY_PROFILE_SUCCESS';
export const REQUEST_MY_PROFILE_FAIL = 'REQUEST_MY_PROFILE_FAIL';

//alert
export const ADD_SIDE_ALERT = 'ADD_SIDE_ALERT';
export const DELETE_SIDE_ALERT = 'DELETE_SIDE_ALERT';

//disposable
export const ADD_EDITING_USER = 'ADD_EDITING_USER';
export const ADD_EDITING_ROLE = 'ADD_EDITING_ROLE';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_VALIDATION = 'ADD_VALIDATION';
export const CLEAR_DISPOSABLE = 'CLEAR_DISPOSABLE';

//Access user
export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAIL = 'REQUEST_USER_FAIL';
export const DO_ASYNC_ACTION = 'DO_ASYNC_ACTION';
export const DONE_ASYNC_ACTION = 'DONE_ASYNC_ACTION';
//Access roles
export const REQUEST_ROLES = 'REQUEST_ROLES';
export const REQUEST_ROLES_SUCCESS = 'REQUEST_ROLES_SUCCESS';
export const REQUEST_ROLES_FAIL = 'REQUEST_ROLES_FAIL';
export const DO_ROLE_ASYNC_ACTION = 'DO_ROLE_ASYNC_ACTION';
export const DONE_ROLE_ASYNC_ACTION = 'DONE_ROLE_ASYNC_ACTION';
//Access permissions
export const REQUEST_PERMISSIONS = 'REQUEST_PERMISSIONS';
export const REQUEST_PERMISSIONS_SUCCESS = 'REQUEST_PERMISSIONS_SUCCESS';
export const REQUEST_PERMISSIONS_FAIL = 'REQUEST_PERMISSIONS_FAIL';
export const REQUEST_PERMISSION_DEPENDENCY_SUCCESS = 'REQUEST_PERMISSION_DEPENDENCY_SUCCESS';
export const REQUEST_PERMISSION_DEPENDENCY_FAIL = 'REQUEST_PERMISSION_DEPENDENCY_FAIL';

export const ADD_DEPENDENCY = 'ADD_DEPENDENCY';
export const CLEAR_DEPENDENCY = 'CLEAR_DEPENDENCY';

export const DO_PERMISSION_ASYNC_ACTION = 'DO_PERMISSION_ASYNC_ACTION';
export const DONE_PERMISSION_ASYNC_ACTION = 'DONE_PERMISSION_ASYNC_ACTION';


//pin
export const REQUEST_PINS = 'REQUEST_PINS';
export const REQUEST_PINS_SUCCESS = 'REQUEST_PINS_SUCCESS';
export const REQUEST_PINS_FAIL = 'REQUEST_PINS_FAIL';
export const DO_ASYNC_GENERATE_PINS = 'DO_ASYNC_GENERATE_PINS';
export const DONE_ASYNC_GENERATE_PINS = 'DONE_ASYNC_GENERATE_PINS';

export const UPDATE_USERINFO_TICKETS = 'UPDATE_USERINFO_TICKETS';
export const UPDATE_USERINFO_RESERVATION = 'UPDATE_USERINFO_RESERVATION';

export const CHANGE_PASS = 'CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';

//message
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//timetable
export const SET_TYPE_STATUS = 'SET_TYPE_STATUS';
export const CHANGE_TYPE_CHECKED = 'CHANGE_TYPE_CHECKED';

export const SET_PLACE_STATUS = 'SET_PLACE_STATUS';
export const CHANGE_PLACE_ACTIVE = 'CHANGE_PLACE_ACTIVE';
export const CHANGE_PLACE_CHECKED = 'CHANGE_PLACE_CHECKED';

export const CHANGE_WEEK = 'CHANGE_WEEK';

export const REQUEST_TIMETABLE = 'REQUEST_TIMETABLE';
export const REQUEST_TIMETABLE_SUCCESS = 'REQUEST_TIMETABLE_SUCCESS';
export const REQUEST_TIMETABLE_FAIL = 'REQUEST_TIMETABLE_FAIL';
export const UPDATE_TIMETABLE = 'UPDATE_TIMETABLE';
export const SET_PLANS = 'SET_PLANS';

//type
export const REQUEST_TYPES = 'REQUEST_TYPES';
export const REQUEST_TYPES_SUCCESS = 'REQUEST_TYPES_SUCCESS';
export const REQUEST_TYPES_FAIL = 'REQUEST_TYPES_FAIL';

export const UPDATE_TYPES = 'UPDATE_TYPES';
export const UPDATE_TYPES_SUCCESS = 'UPDATE_TYPES_SUCCESS';
export const UPDATE_TYPES_FAIL = 'UPDATE_TYPES_FAIL';

export const CREATE_TYPES = 'CREATE_TYPES';
export const CREATE_TYPES_SUCCESS = 'CREATE_TYPES_SUCCESS';
export const CREATE_TYPES_FAIL = 'CREATE_TYPES_FAIL';

export const DELETE_TYPES = 'DELETE_TYPES';
export const DELETE_TYPES_SUCCESS = 'DELETE_TYPES_SUCCESS';
export const DELETE_TYPES_FAIL = 'DELETE_TYPES_FAIL';

//disposable
export const ADD_DISPOSABLE_PLAN = 'ADD_DISPOSABLE_PLAN';

export const CREATE_TYPE = 'CREATE_TYPE';
export const CREATE_TYPE_SUCCESS = 'CREATE_TYPE_SUCCESS';
export const CREATE_TYPE_FAIL = 'CREATE_TYPE_FAIL';


//flight
export const UPDATE_FLIGHT = 'UPDATE_FLIGHT';
export const UPDATE_FLIGHT_SUCCESS = 'UPDATE_FLIGHT_SUCCESS';
export const UPDATE_FLIGHT_FAIL = 'UPDATE_FLIGHT_FAIL';

export const OPEN_FLIGHT = 'OPEN_FLIGHT';
export const OPEN_FLIGHT_SUCCESS = 'OPEN_FLIGHT_SUCCESS';
export const OPEN_FLIGHT_FAIL = 'OPEN_FLIGHT_FAIL';

export const CLOSE_FLIGHT = 'CLOSE_FLIGHT';
export const CLOSE_FLIGHT_SUCCESS = 'CLOSE_FLIGHT_SUCCESS';
export const CLOSE_FLIGHT_FAIL = 'CLOSE_FLIGHT_FAIL';
