export const REQUEST_PLACES = 'REQUEST_PLACES';
export const REQUEST_PLACES_SUCCESS = 'REQUEST_PLACES_SUCCESS';
export const REQUEST_PLACES_FAIL = 'REQUEST_PLACES_FAIL';

export const UPDATE_PLACE = 'UPDATE_PLACE';
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const UPDATE_PLACE_FAIL = 'UPDATE_PLACE_FAIL';

export const CREATE_PLACE = 'CREATE_PLACE';
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS';
export const CREATE_PLACE_FAIL = 'CREATE_PLACE_FAIL';

export const DELETE_PLACE = 'DELETE_PLACE';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';
export const DELETE_PLACE_FAIL = 'DELETE_PLACE_FAIL';
