export const REQUEST_PLANS = 'REQUEST_PLANS';
export const REQUEST_PLANS_SUCCESS = 'REQUEST_PLANS_SUCCESS';
export const REQUEST_PLANS_FAIL = 'REQUEST_PLANS_FAIL';

export const REQUEST_PLAN = 'REQUEST_PLAN';
export const REQUEST_PLAN_SUCCESS = 'REQUEST_PLAN_SUCCESS';
export const REQUEST_PLAN_FAIL = 'REQUEST_PLAN_FAIL';

export const CREATE_PLAN = 'CREATE_PLAN';
export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS';
export const CREATE_PLAN_FAIL = 'CREATE_PLAN_FAIL';

export const UPDATE_PLAN = 'UPDATE_PLAN';
export const UPDATE_PLAN_SUCCESS = 'UPDATE_PLAN_SUCCESS';
export const UPDATE_PLAN_FAIL = 'UPDATE_PLAN_FAIL';

export const ACTIVATE_PLAN = 'ACTIVATE_PLAN';
export const ACTIVATE_PLAN_SUCCESS = 'ACTIVATE_PLAN_SUCCESS';
export const ACTIVATE_PLAN_FAIL = 'ACTIVATE_PLAN_FAIL';

export const DEACTIVATE_PLAN = 'DEACTIVATE_PLAN';
export const DEACTIVATE_PLAN_SUCCESS = 'DEACTIVATE_PLAN_SUCCESS';
export const DEACTIVATE_PLAN_FAIL = 'DEACTIVATE_PLAN_FAIL';

export const DELETE_PLAN = 'DELETE_PLAN';
export const DELETE_PLAN_SUCCESS = 'DELETE_PLAN_SUCCESS';
export const DELETE_PLAN_FAIL = 'DELETE_PLAN_FAIL';

export const REQUEST_CLOSED_PLACES = 'REQUEST_CLOSED_PLACES';
export const REQUEST_CLOSED_PLACES_SUCCESS = 'REQUEST_CLOSED_PLACES_SUCCESS';
export const REQUEST_CLOSED_PLACES_FAIL = 'REQUEST_CLOSED_PLACES_FAIL';
