export const REQUEST_CHARTS = 'REQUEST_CHARTS';
export const REQUEST_CHARTS_SUCCESS = 'REQUEST_CHARTS_SUCCESS';
export const REQUEST_CHARTS_FAIL = 'REQUEST_CHARTS_FAIL';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS';
export const REQUEST_MESSAGES_FAIL = 'REQUEST_MESSAGES_FAIL';




export const REQUEST_CHARTS_TEST = 'REQUEST_CHARTS_TEST';
export const REQUEST_CHARTS_TEST_SUCCESS = 'REQUEST_CHARTS_TEST_SUCCESS';
export const REQUEST_CHARTS_TEST_FAIL = 'REQUEST_CHARTS_TEST_FAIL';
