export const REQUEST_LECTURES = 'REQUEST_LECTURES';
export const REQUEST_LECTURES_SUCCESS = 'REQUEST_LECTURES_SUCCESS';
export const REQUEST_LECTURES_FAIL = 'REQUEST_LECTURES_FAIL';

export const REQUEST_LECTURE = 'REQUEST_LECTURE';
export const REQUEST_LECTURE_SUCCESS = 'REQUEST_LECTURE_SUCCESS';
export const REQUEST_LECTURE_FAIL = 'REQUEST_LECTURE_FAIL';

export const REQUEST_ROOM = 'REQUEST_ROOM';
export const REQUEST_ROOM_SUCCESS = 'REQUEST_ROOM_SUCCESS';
export const REQUEST_ROOM_FAIL = 'REQUEST_ROOM_FAIL';

export const REQUEST_LECTURE_BASIC = 'REQUEST_LECTURE_BASIC';
export const REQUEST_LECTURE_BASIC_SUCCESS = 'REQUEST_LECTURE_BASIC_SUCCESS';
export const REQUEST_LECTURE_BASIC_FAIL = 'REQUEST_LECTURE_BASIC_FAIL';

export const REQUEST_SEARCH_LECTURE = 'REQUEST_SEARCH_LECTURE';
export const REQUEST_SEARCH_LECTURE_SUCCESS = 'REQUEST_SEARCH_LECTURE_SUCCESS';
export const REQUEST_SEARCH_LECTURE_FAIL = 'REQUEST_SEARCH_LECTURE_FAIL';

export const STORE_LECTURE = 'STORE_LECTURE';
export const STORE_LECTURE_SUCCESS = 'STORE_LECTURE_SUCCESS';
export const STORE_LECTURE_FAIL = 'STORE_LECTURE_FAIL';

export const JOIN_LECTURE = 'JOIN_LECTURE';
export const JOIN_LECTURE_SUCCESS = 'JOIN_LECTURE_SUCCESS';
export const JOIN_LECTURE_FAIL = 'JOIN_LECTURE_FAIL';

export const OPEN_ROOM = 'OPEN_ROOM';
export const OPEN_ROOM_SUCCESS = 'OPEN_ROOM_SUCCESS';
export const OPEN_ROOM_FAIL = 'OPEN_ROOM_FAIL';

export const CLOSE_ROOM = 'CLOSE_ROOM';
export const CLOSE_ROOM_SUCCESS = 'CLOSE_ROOM_SUCCESS';
export const CLOSE_ROOM_FAIL = 'CLOSE_ROOM_FAIL';
