export const REQUEST_LECTURES = 'REQUEST_LECTURES';
export const REQUEST_LECTURES_SUCCESS = 'REQUEST_LECTURES_SUCCESS';
export const REQUEST_LECTURES_FAIL = 'REQUEST_LECTURES_FAIL';

export const REQUEST_LECTURE = 'REQUEST_LECTURE';
export const REQUEST_LECTURE_SUCCESS = 'REQUEST_LECTURE_SUCCESS';
export const REQUEST_LECTURE_FAIL = 'REQUEST_LECTURE_FAIL';

export const REQUEST_ROOM = 'REQUEST_ROOM';
export const REQUEST_ROOM_SUCCESS = 'REQUEST_ROOM_SUCCESS';
export const REQUEST_ROOM_FAIL = 'REQUEST_ROOM_FAIL';
