export const REQUEST_USER_INFORMATION = 'REQUEST_USER_INFORMATION';
export const REQUEST_USER_INFORMATION_SUCCESS = 'REQUEST_USER_INFORMATION_SUCCESS';
export const REQUEST_USER_INFORMATION_FAIL = 'REQUEST_USER_INFORMATION_FAIL';
