<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class StudentTableSeeder
 */
class StudentTableSeeder extends Seeder
{
    public function run()
    {
        if(config('database.connections')[config('database.default')]['driver'] == 'mysql'){
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        if(config('database.connections')[config('database.default')]['driver'] == 'mysql'){
            DB::table('students')->truncate();
        } elseif (env('DB_CONNECTION') == 'sqlite') {
            DB::statement('DELETE FROM students');
        } else {
            //For PostgreSQL or anything else
            DB::statement('TRUNCATE TABLE students CASCADE');
        }
        
        $students = [
            [
                'family_name'       => '山田',
                'given_name'        => '太郎',
                'family_name_yomi'  => 'ヤマダ',
                'given_name_yomi'   => 'タロウ',
                'phone'             => '09044444444',
                'sex'               => 1,
                'birthday'          => '1991/01/01',
                'student_id'        => '12345678',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'yamada@gmail.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => 'Jobs',
                'given_name'        => 'Steve',
                'family_name_yomi'  => 'ジョブズ',
                'given_name_yomi'   => 'スティーブ',
                'phone'             => '09044444444',
                'sex'               => 1,
                'birthday'          => '1991/01/01',
                'student_id'        => '12345678',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'test@test.com',
                'password'          => bcrypt('iloveapple'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '鈴木',
                'given_name'        => '花子',
                'family_name_yomi'  => 'スズキ',
                'given_name_yomi'   => 'ハナコ',
                'phone'             => '09022222222',
                'sex'               => 0,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'suzuki@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '前川',
                'given_name'        => '知世',
                'family_name_yomi'  => 'マエカワ',
                'given_name_yomi'   => 'トモヨ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'maekawa@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '西島',
                'given_name'        => '利恵',
                'family_name_yomi'  => 'ニシジマ',
                'given_name_yomi'   => 'リエ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'nisizima@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '江田',
                'given_name'        => 'まみ',
                'family_name_yomi'  => 'エダ',
                'given_name_yomi'   => 'マミ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'eda@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '如月',
                'given_name'        => '恵里子',
                'family_name_yomi'  => 'キサラギ',
                'given_name_yomi'   => 'エリコ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'kisaragi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '古畑',
                'given_name'        => '綾花',
                'family_name_yomi'  => 'フルハタ',
                'given_name_yomi'   => 'アヤカ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'furuhata@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '芹沢',
                'given_name'        => '聖子',
                'family_name_yomi'  => 'セリザワ',
                'given_name_yomi'   => 'ショウコ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'serizawa@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '菅澤',
                'given_name'        => '理加',
                'family_name_yomi'  => 'スガサワ',
                'given_name_yomi'   => 'リカ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'sugasawa@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '平藤',
                'given_name'        => '麗実',
                'family_name_yomi'  => 'ヒラトウ',
                'given_name_yomi'   => 'レミ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'hirato@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '紙谷',
                'given_name'        => '夏樹',
                'family_name_yomi'  => 'カミヤ',
                'given_name_yomi'   => 'ナツキ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'kamiya@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '安宅',
                'given_name'        => '友里子',
                'family_name_yomi'  => 'アタカ',
                'given_name_yomi'   => 'ユリコ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'ataka@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '徐',
                'given_name'        => '江梨',
                'family_name_yomi'  => 'ソ',
                'given_name_yomi'   => 'エリ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'so@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '中路',
                'given_name'        => '絹代',
                'family_name_yomi'  => 'ナカジ',
                'given_name_yomi'   => 'キヌヨ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'nakazi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '川角',
                'given_name'        => '実央',
                'family_name_yomi'  => 'カワスミ',
                'given_name_yomi'   => 'ミオ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'kawasumi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '関塚',
                'given_name'        => '美砂子',
                'family_name_yomi'  => 'セキヅカ',
                'given_name_yomi'   => 'ミサコ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'sekiduka@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '川橋',
                'given_name'        => '温美',
                'family_name_yomi'  => 'カワハシ',
                'given_name_yomi'   => 'アツミ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'kawahasi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '千足',
                'given_name'        => '由有',
                'family_name_yomi'  => 'チアシ',
                'given_name_yomi'   => 'ユウ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'tiasi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '尾井',
                'given_name'        => '咲耶',
                'family_name_yomi'  => 'オイ',
                'given_name_yomi'   => 'サヤ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'oi@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '須納瀬',
                'given_name'        => '恭江',
                'family_name_yomi'  => 'スノセ',
                'given_name_yomi'   => 'ヤスエ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'sunose@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ],[
                'family_name'       => '福迫',
                'given_name'        => '由梨乃',
                'family_name_yomi'  => 'フクサコ',
                'given_name_yomi'   => 'ユリコ',
                'phone'             => '09022222222',
                'sex'               => 1,
                'birthday'          => '1992/01/01',
                'student_id'        => '92345679',
                'postal_code'       => 3334444,
                'state'             => '愛知県',
                'city'              => '名古屋市千種区',
                'street'            => '不老町',
                'building'          => '',
                'introduction'      => '自己紹介です',
                'email'             => 'fukusako@react-opt.com',
                'password'          => bcrypt('123456'),
                'api_token'         => md5(uniqid(mt_rand(), true)),
                'confirmation_code' => md5(uniqid(mt_rand(), true)),
                'confirmed'         => true,
                'created_at'        => Carbon::now(),
                'updated_at'        => Carbon::now(),
            ]
        ];

        DB::table('students')->insert($students);

        if(config('database.connections')[config('database.default')]['driver'] == 'mysql'){
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }
    }
}