export const REQUEST_CONFERENCE = 'REQUEST_CONFERENCE';
export const REQUEST_CONFERENCE_SUCCESS = 'REQUEST_CONFERENCE_SUCCESS';
export const REQUEST_CONFERENCE_FAIL = 'REQUEST_CONFERENCE_FAIL';

export const CREATE_AUDITOR = 'CREATE_AUDITOR';
export const CREATE_AUDITOR_SUCCESS = 'CREATE_AUDITOR_SUCCESS';
export const CREATE_AUDITOR_FAIL = 'CREATE_AUDITOR_FAIL';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const REQUEST_MESSAGES_SUCCESS = 'REQUEST_MESSAGES_SUCCESS';
export const REQUEST_MESSAGES_FAIL = 'REQUEST_MESSAGES_FAIL';

export const SEND_MESSAGES = 'SEND_MESSAGES';
export const SEND_MESSAGES_SUCCESS = 'SEND_MESSAGES_SUCCESS';
export const SEND_MESSAGES_FAIL = 'SEND_MESSAGES_FAIL';

export const SEND_LIKE = 'SEND_LIKE';
export const SEND_LIKE_SUCCESS = 'SEND_LIKE_SUCCESS';
export const SEND_LIKE_FAIL = 'SEND_LIKE_FAIL';

export const SEND_DISLIKE = 'SEND_DISLIKE';
export const SEND_DISLIKE_SUCCESS = 'SEND_DISLIKE_SUCCESS';
export const SEND_DISLIKE_FAIL = 'SEND_DISLIKE_FAIL';
